name: Staging deployment

on:
  push:
    tags:
    - stage-*

jobs: 
  deploy:
   
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
         
      - name: Deploy
        run: pm2 restart bot

    

